# Generated by Django 5.2.5 on 2025-08-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_is_pinned_note_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
